/* dialogue.js — questions answered only from passages of this book.
   Retrieval runs in the browser over the shipped text; only the passages it
   selects and the question are sent onward. */
import { esc, chapChip, retrieve } from "./app.js";

const el = h => { const t = document.createElement("template"); t.innerHTML = h.trim(); return t.content.firstElementChild; };

const MODES = [
  ["teaching", "Explain it", "Explains as the book explains, in its own terms."],
  ["locate", "Where does it say that?", "Points to the chapters that bear on the question."],
  ["critical", "What does it not settle?", "Marks where the passages stop short of an answer."],
];

const verlauf = [];

export function renderDialogue(view) {
  view.append(el(`<div>
    <div class="viewhead"><span class="tag">Dialogue</span>
      <h1>Ask the book</h1>
      <p class="lede">Retrieval runs in your browser and picks passages from the text. Only those passages
      and your question are sent onward; the answer must stay within them and name the chapter it draws
      on.</p></div>

    <div class="panel">
      <div class="toolbar">
        <select id="dmode">${MODES.map(([v, l]) => `<option value="${v}">${l}</option>`).join("")}</select>
        <span class="fine" id="dhint">${MODES[0][2]}</span>
      </div>
      <textarea id="dq" rows="3" placeholder="e.g. What is the difference between a research question and a regular question?"></textarea>
      <div class="btnrow">
        <button class="primary" id="dsend">Ask</button>
        <span class="fine" id="dstate"></span>
      </div>
      <p class="fine">A study aid, not a marker. It cannot tell you whether your own argument is any good,
      and it will not answer beyond what the book says.</p>
    </div>
    <div id="dout"></div>
  </div>`));

  const q = view.querySelector("#dq"), out = view.querySelector("#dout");
  const state = view.querySelector("#dstate"), btn = view.querySelector("#dsend");
  const mode = view.querySelector("#dmode"), hint = view.querySelector("#dhint");
  mode.onchange = () => { hint.textContent = (MODES.find(m => m[0] === mode.value) || MODES[0])[2]; };

  btn.onclick = async () => {
    const frage = q.value.trim();
    if (frage.length < 5) { state.textContent = "Please formulate a question."; return; }
    btn.disabled = true; state.textContent = "Finding passages …";

    const treffer = retrieve(frage, 10);
    if (!treffer.length) {
      state.textContent = "";
      out.prepend(el(`<div class="statebox warn">No passage matches closely enough. Try wording it with
        terms the book uses — the <a href="#/glossary">glossary</a> is a good place to look.</div>`));
      btn.disabled = false; return;
    }

    const passagen = treffer.map(t => ({
      zitat: `${t.chap.titel}${t.chap.seite_von ? `, p. ${t.chap.seite_von}` : ""}`,
      werk: t.chap.teil_titel, text: t.text,
    }));
    verlauf.push({ rolle: "user", text: frage });
    state.textContent = `Asking with ${passagen.length} passages …`;

    let data;
    try {
      const r = await fetch("/.netlify/functions/dialogue", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ frage, modus: mode.value, passagen, verlauf }),
      });
      data = await r.json();
    } catch (e) { data = { error: String(e && e.message ? e.message : e) }; }
    state.textContent = ""; btn.disabled = false;

    if (data.error) {
      out.prepend(el(`<div class="statebox warn">${esc(data.error)}</div>`));
      verlauf.pop();
      return;
    }
    verlauf.push({ rolle: "assistant", text: data.antwort });

    out.prepend(el(`<div class="panel answer">
      <h2>${esc(frage)}</h2>
      <div class="readable">${data.antwort.split(/\n{2,}/).map(p => `<p>${esc(p)}</p>`).join("")}</div>
      <details class="evidence"><summary>${treffer.length} passages this answer was bound to</summary>
        <ul>${treffer.map(t => `<li>${chapChip(t.chap)}
          <p class="readable" style="font-size:.9rem">${esc(t.text.slice(0, 400))}${t.text.length > 400 ? "…" : ""}</p>
        </li>`).join("")}</ul></details>
      <p class="fine">Generated by a language model bound to the passages above, which you can read in full
      under <a href="#/contents">Contents</a>.</p>
    </div>`));
    q.value = "";
  };
}
